In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("bycycle accident in great britain.csv")
df.head(10)

,index,Accident_Index,Number_of_Vehicles,Number_of_Casualties,Date,Time,Speed_limit,Road_conditions,Weather_conditions,Day,Road_type,Light_conditions
0,0,197901A1SEE71,2,1,01-01-79,18:20,50,Snow,Unknown,Monday,Dual carriageway,Darkness lights lit
1,1,197901A2JDW40,1,1,01-02-79,9:15,30,Snow,Unknown,Tuesday,Unknown,Daylight
2,2,197901A4IJV90,2,1,01-04-79,8:45,30,Snow,Unknown,Thursday,Unknown,Daylight
3,3,197901A4NIE33,2,1,01-04-79,13:40,30,Wet,Unknown,Thursday,Unknown,Daylight
4,4,197901A4SKO47,2,1,01-04-79,18:50,30,Wet,Unknown,Thursday,Unknown,Darkness lights lit
5,5,197901A5CKE54,2,1,01-05-79,2:50,40,Snow,Unknown,Friday,Dual carriageway,Darkness lights lit
6,6,197901A5UJC75,2,1,01-05-79,20:45,30,Wet,Unknown,Friday,Single carriageway,Darkness lights lit
7,7,197901A6ODP50,2,1,01-06-79,14:15,70,Snow,Unknown,Saturday,Unknown,Daylight
8,8,197901A6VEC34,2,1,01-06-79,21:20,30,Wet,Unknown,Saturday,Roundabout,Darkness lights lit
9,9,197901A7PDD49,2,1,01-07-79,15:15,30,Wet,Rain,Sunday,Unknown,Daylight

In [3]:
#df = pd.read_excel("bycycle accident in great britain.xlsx")
#df.head(10)

In [4]:
#sns.pairplot(df)

In [5]:
 df.shape

(827861, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 827861 entries, 0 to 827860
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   index                 827861 non-null  int64
 1   Accident_Index        827861 non-null  object
 2   Number_of_Vehicles    827861 non-null  int64
 3   Number_of_Casualties  827861 non-null  int64
 4   Date                  827861 non-null  object
 5   Time                  827861 non-null  object
 6   Speed_limit           827861 non-null  int64
 7   Road_conditions       827861 non-null  object
 8   Weather_conditions    827861 non-null  object
 9   Day                   827861 non-null  object
 10  Road_type             827861 non-null  object
 11  Light_conditions      827861 non-null  object
dtypes: int64(4), object(8)
memory usage: 75.8+ MB

In [7]:
df.isnull().sum()

index                   0
Accident_Index          0
Number_of_Vehicles      0
Number_of_Casualties    0
Date                    0
Time                    0
Speed_limit             0
Road_conditions         0
Weather_conditions      0
Day                     0
Road_type               0
Light_conditions        0
dtype: int64

In [8]:
x = df.drop(["index","Date","Day","Accident_Index","Time"],axis = 1)
x.head(10)

,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Road_conditions,Weather_conditions,Road_type,Light_conditions
0,2,1,50,Snow,Unknown,Dual carriageway,Darkness lights lit
1,1,1,30,Snow,Unknown,Unknown,Daylight
2,2,1,30,Snow,Unknown,Unknown,Daylight
3,2,1,30,Wet,Unknown,Unknown,Daylight
4,2,1,30,Wet,Unknown,Unknown,Darkness lights lit
5,2,1,40,Snow,Unknown,Dual carriageway,Darkness lights lit
6,2,1,30,Wet,Unknown,Single carriageway,Darkness lights lit
7,2,1,70,Snow,Unknown,Unknown,Daylight
8,2,1,30,Wet,Unknown,Roundabout,Darkness lights lit
9,2,1,30,Wet,Rain,Unknown,Daylight

In [9]:
y = df["index"]
y.head(10)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: index, dtype: int64

In [10]:
y.dtypes

dtype('int64')

In [11]:
x.dtypes

Number_of_Vehicles       int64
Number_of_Casualties     int64
Speed_limit              int64
Road_conditions         object
Weather_conditions      object
Road_type               object
Light_conditions        object
dtype: object

In [12]:
#Accident_Index = pd.get_dummies(y["Accident_Index"],dtype=int)
#Accident_Index.head(10)

# one hot encoding

In [13]:
Road_conditions = pd.get_dummies(x["Road_conditions"],dtype=int)
Road_conditions.head(10)

   Dry  Flood  Frost  Missing Data  Snow  Wet
0    0      0      0             0     1    0
1    0      0      0             0     1    0
2    0      0      0             0     1    0
3    0      0      0             0     0    1
4    0      0      0             0     0    1
5    0      0      0             0     1    0
6    0      0      0             0     0    1
7    0      0      0             0     1    0
8    0      0      0             0     0    1
9    0      0      0             0     0    1

In [14]:
Weather_conditions = pd.get_dummies(x["Weather_conditions"],dtype=int)
Weather_conditions.head(10)

,Clear,Clear and windy,Fog,Missing data,Other,Rain,Rain and windy,Snow,Snow and windy,Unknown
0,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,1,0,0,0,0

In [15]:
Road_type = pd.get_dummies(x["Road_type"],prefix="encoded",dtype=int)
Road_type.head(10)

,encoded_Dual carriageway,encoded_One way sreet,encoded_Roundabout,encoded_Single carriageway,encoded_Slip road,encoded_Unknown
0,1,0,0,0,0,0
1,0,0,0,0,0,1
2,0,0,0,0,0,1
3,0,0,0,0,0,1
4,0,0,0,0,0,1
5,1,0,0,0,0,0
6,0,0,0,1,0,0
7,0,0,0,0,0,1
8,0,0,1,0,0,0
9,0,0,0,0,0,1

In [16]:
Light_conditions = pd.get_dummies(x["Light_conditions"],prefix="encoded",dtype=int)
Light_conditions.head(10)

   encoded_Darkness lights lit  encoded_Darkness no lights  encoded_Daylight
0                            1                           0                 0
1                            0                           0                 1
2                            0                           0                 1
3                            0                           0                 1
4                            1                           0                 0
5                            1                           0                 0
6                            1                           0                 0
7                            0                           0                 1
8                            1                           0                 0
9                            0                           0                 1

# drop encoded properties

In [21]:
x = df.drop(["Road_conditions","Light_conditions","Road_type","Weather_conditions","index","Date","Day","Accident_Index","Time"],axis = 1)
x.head(10)

   Number_of_Vehicles  Number_of_Casualties  Speed_limit
0                   2                     1           50
1                   1                     1           30
2                   2                     1           30
3                   2                     1           30
4                   2                     1           30
5                   2                     1           40
6                   2                     1           30
7                   2                     1           70
8                   2                     1           30
9                   2                     1           30

# concate properties

In [22]:
x=pd.concat([x,Road_conditions,Light_conditions,Road_type,Weather_conditions],axis=1)
x.head(10)

,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Dry,Flood,Frost,Missing Data,Snow,Wet,encoded_Darkness lights lit,...,Clear,Clear and windy,Fog,Missing data,Other,Rain,Rain and windy,Snow,Snow and windy,Unknown
0,2,1,50,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
1,1,1,30,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,1,30,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,2,1,30,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,2,1,30,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
5,2,1,40,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
6,2,1,30,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
7,2,1,70,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,2,1,30,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
9,2,1,30,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [23]:
 x.dtypes

Number_of_Vehicles             int64
Number_of_Casualties           int64
Speed_limit                    int64
Dry                            int32
Flood                          int32
Frost                          int32
Missing Data                   int32
Snow                           int32
Wet                            int32
encoded_Darkness lights lit    int32
encoded_Darkness no lights     int32
encoded_Daylight               int32
encoded_Dual carriageway       int32
encoded_One way sreet          int32
encoded_Roundabout             int32
encoded_Single carriageway     int32
encoded_Slip road              int32
encoded_Unknown                int32
Clear                          int32
Clear and windy                int32
Fog                            int32
Missing data                   int32
Other                          int32
Rain                           int32
Rain and windy                 int32
Snow                           int32
Snow and windy                 int32
Unknown                        int32
dtype: object

In [26]:
 y.dtypes

dtype('int64')

# train_test_split

In [27]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [28]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25,random_state=1)

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
regressor = LinearRegression()

In [31]:
regressor.fit(xtrain,ytrain)

LinearRegression()

# predict the test result

In [32]:
xtest

,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Dry,Flood,Frost,Missing Data,Snow,Wet,encoded_Darkness lights lit,...,Clear,Clear and windy,Fog,Missing data,Other,Rain,Rain and windy,Snow,Snow and windy,Unknown
490124,2,1,30,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
366355,2,1,30,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
317766,2,1,40,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
218554,1,1,30,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
401944,2,1,30,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389096,2,1,30,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
89469,3,3,30,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
570323,2,1,30,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
437419,1,1,60,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
317303,2,1,30,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0

In [33]:
ytest

490124    490124
366355    366355
317766    317766
218554    218554
401944    401944
           ...
389096    389096
89469      89469
570323    570323
437419    437419
317303    317303
Name: index, Length: 206966, dtype: int64

# prediction

In [35]:
pred = regressor.predict(xtest)
pred

array([426394., 426394., 412088., ..., 446088., 390208., 492366.])

# R squared value

In [36]:
regressor.score(xtest,ytest)

0.06313594598947991

In [38]:
from sklearn.metrics import r2_score
score = r2_score(ytest,pred)
score

0.06313594598947991